# .railway.toml
[build]
builder       = "NIXPACKS"
buildCommand  = "npm run build"  # Standard build command

[deploy]
# 1. Push / migrate DB before starting
preDeployCommand = "npm run db:push"

# 2. Boot your server (tsx compiles TypeScript onthefly)
startCommand  = "NODE_ENV=production tsx server/index.ts"

# 3. Healthcheck + restart policy
healthcheckPath        = "/health"
healthcheckTimeout     = 180            # seconds
restartPolicyType      = "ON_FAILURE"
restartPolicyMaxRetries = 10

# 4. Environment variables for Railway-specific build
[variables]
NIXPACKS_PKGS = "fontconfig fontconfig-dev harfbuzz harfbuzz-dev freetype freetype-dev icu texlive-fonts-recommended texlive-fonts-extra texlive-latex-base texlive-latex-recommended"
VITE_APP_CHUNK_SIZE_WARNING_LIMIT = "1000"