# .railway.toml

[build]
builder       = "NIXPACKS"
buildCommand  = "npm run build"          # runs: vite build

# Tell Nixpacks to install Tectonic
[build.nixpacks]
pkgs = ["tectonic"]

[deploy]
# 1. Push / migrate DB before starting
preDeployCommand = "npm run db:push"

# 2. Boot your server (tsx compiles TypeScript on the fly)
startCommand  = "NODE_ENV=production tsx server/index.ts"

# 3. Healthcheck + restart policy
healthcheckPath        = "/health"
healthcheckTimeout     = 180            # seconds
restartPolicyType      = "ON_FAILURE"
restartPolicyMaxRetries = 10