# .railway.toml

[build]
builder             = "NIXPACKS"
buildCommand        = "npm run build"
postBuildCommand    = "echo 'Build complete'"

[deploy]
preDeployCommand    = "npm run db:push"
startCommand        = "NODE_ENV=production tsx server/index.ts"

healthcheckPath     = "/health"
healthcheckTimeout  = 180
restartPolicyType   = "ON_FAILURE"
restartPolicyMaxRetries = 10