# nixpacks.toml

# 1) Add Node + Tectonic to your setup environment
[phases.setup]
nixPkgs = [
  "nodejs_18",   # or "nodejs_20" if you prefer
  "tectonic"
]

# 2) Explicitly define your install, build, and start commands
[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[phases.start]
cmds = [
  "NODE_ENV=production tsx server/index.ts"
]