# nixpacks.toml - Configuration for Railway deployment

[phases.setup]
nixPkgs = [
  # Runtime environments
  "nodejs_20",
  "nodePackages.typescript",
  # Tectonic and its dependencies
  "tectonic",
  "fontconfig",
  "harfbuzz",
  "openssl",
  # Ensure necessary fonts are available
  "dejavu_fonts", 
  "cm_unicode",
  "lmodern",
  # Note: latin-modern-math was removed - package doesn't exist in Nixpkgs
  # Required for certain LaTeX operations
  "poppler_utils",
  "ghostscript"
]

[phases.build]
cmds = [
  "npm install",
  "npm run build"
]

[phases.deploy]
cmds = [
  "npm run db:push"
]

[start]
cmd = "NODE_ENV=production NODE_PATH=. npx tsx server/index.ts"