[phases.setup]
aptPkgs = ["build-essential", "fontconfig", "libfontconfig1-dev", "libharfbuzz-dev", "libfreetype6-dev", "libgraphite2-dev", "libicu-dev", "libssl-dev", "zlib1g-dev", "curl", "unzip", "texlive-fonts-recommended", "texlive-fonts-extra", "texlive-latex-base", "texlive-latex-recommended", "texlive-science", "texlive-pictures"]

[phases.build]
cmds = [
  "curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net | sh",
  "chmod +x tectonic",
  "mv tectonic /usr/local/bin/",
  "tectonic --version"
]

[phases.install]
cmds = [
  "npm run build"
]

[start]
cmd = "NODE_ENV=production tsx server/index.ts"